variables:
  ECR_REGISTRY: ${ECR_ADDRESS}
  IMAGE_TAG: devopsconf-demo:$CI_COMMIT_SHA
  REGION: eu-central-1
  K8S_CLUSTER_NAME: eks-spot-workshop
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
- build
- deploy
- test

build_image:
  stage: build
  image: docker:20.10.6
  before_script:
    - docker info
    - apk add --no-cache curl python3 py3-pip
    - curl -s http://169.254.169.254/latest/meta-data/hostname
    - curl -s http://169.254.169.254/latest/meta-data/placement/region
    - pip install awscli
    - aws --version
    - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $ECR_REGISTRY/$IMAGE_TAG
    - docker push $ECR_REGISTRY/$IMAGE_TAG

deploy_to_eks:
  stage: deploy
  script:
    - echo "Ok!"

test_on_eks:
  stage: test
  script:
    - echo "Ok!"